/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;

import org.junit.Rule;
import org.junit.jupiter.api.Test;
import org.junit.rules.ExpectedException;
import processing.core.PApplet;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Rule
    public ExpectedException exceptionRule = ExpectedException.none();

    @Test
    public void createAppTest() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "Unable to create App instance.");
    }

    @Test
    public void setupTest() {
        App app = new App();
        PApplet.runSketch(new String[] {"Test Sketch"}, app);
        app.setup();

        assertTrue(app.frameRate > 0, "Incorrectly setup framerate.");
        assertNotNull(app.gameInstance, "Unable to create Game instance.");
    }

    @Test
    public void settingsTest() {
        App app = new App();
        PApplet.runSketch(new String[] {"Test Sketch"}, app);
        app.settings();
        assertEquals(app.WIDTH, app.width, "Incorrectly setup app width");
        assertEquals(app.HEIGHT, app.height, "Incorrectly setup app height");
    }

    @Test
    public void mainTest() {
        App app = new App();
        PApplet.runSketch(new String[] {"Test Sketch"}, app);
        app.settings();

        String[] args = new String[0];
        App.main(args);
        assertNotNull(app, "Unable to create App instance.");
    }
}
